name: Upload Resume to Naukri

on:
  schedule:
    - cron: '30 1 * * *'  # Runs daily at 7:00 AM IST (1:30 AM UTC)
  workflow_dispatch:       # Allows manual trigger from GitHub UI

jobs:
  upload-resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file from secrets
        run: |
          echo "NAUKRI_EMAIL=${{ secrets.NAUKRI_EMAIL }}" >> .env
          echo "NAUKRI_PASSWORD=${{ secrets.NAUKRI_PASSWORD }}" >> .env
          echo "RESUME_PATH=${{ secrets.RESUME_PATH }}" >> .env

      - name: Run Puppeteer script
        run: node upload.js
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
          RESUME_PATH: ${{ secrets.RESUME_PATH }}
